kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'anyuid-rb'
subjects:
  - kind: ServiceAccount
    name: ibm-cp4ba-anyuid
    namespace: cp4ba-starter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
