kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-file-gold-gid
  volumeMode: Filesystem
