kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-job-bai-kibana-init
subjects:
  - kind: ServiceAccount
    name: sa-job-bai-kibana-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-job-bai-kibana-init
