apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-cert-manager-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - watch
      - list
      - create
      - patch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
      - operatorgroups
    verbs:
      - get
      - watch
      - list
