apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - cp4ba-argo-role.yaml
  - cp4ba-argo-rb.yaml

  #- secrets-generator.yaml
  - common.yaml
  - kibana.yaml
  - operator.yaml
  - operand.yaml

patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: group=applications
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/Nordic-MVP-GitOps-Repos/cp4ba.git
    - op: add
      path: /spec/source/targetRevision
      value: bai-standalone
