apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-generator
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: kubernetes-secret-generator
    repoURL: https://github.com/mittwald/kubernetes-secret-generator
    targetRevision: 3.4.0
    helm:
      releaseName: kubernetes-secret-generator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cp4ba-starter
